import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "ado-background": "#FFFFFF",
        "ado-border-green": "#87CE77",
        "ado-date-select": "#E7F7E4",
        "ado-date-background": "#FAFAFA",
        "ado-scroll-background": "#F1F3F9",
        "ado-background-secondary": "#F4F6F9",
        "ado-neutral-light": "#B5BAC7FF",
        "ado-search-border": "#E5E9EE",
        "ado-selected": "#5F2167",
        "ado-red": "#E11F2A",
        "ado-purple": "#5F2167",
        "ado-royal-purple": "#622366",
        "ado-green": "#258910",
        "ado-teal": "#169A8E",
        "ado-light-green": "#87CE77",
        "ado-text-gray": "#1D1F24",
        "ado-text-white": "#F6F7FB",
        "ado-booking-link": "#169A8E",
        "ado-golden": "#D1820B",
        "ado-white": "#FAFBFD",
        "ado-bg-light-gray": "#ECEFF6",
        "ado-sandal": "#FFF1DB",
        "ado-alert-border": "#FFD898",
        "ado-gray": "#E3E7F2",
        "ado-lavendar": "#AF90B3",
        "ado-charcoal": "#1D1F24",
        "ado-steel-gray": "#6F7587",
        "ado-light-purple": "#AF90B3",
        "ado-frost-gray": "#E3E7F2",
        "ado-bg-gray": "#F3F4F6",
        "ado-ice-blue": "#F6F7FB",
        "ado-slate-gray": "#595E6D",
        "ado-light-blue-gray": "#E8EBF4",
        "ado-footer-gray": "#808391",
        "ado-snow-gray": "#FAFAFA",
        "ado-blueish-grey": "#F4F6F9FF",
        "ado-bg-black-40": "#00000066",
        "ado-black": "#000000",
        "ado-accessibility-bar-bg": "#31343C",
        "ado-cool-gray": "#E8EBEE",
        "ado-soft-blue": "#C7D9EC",
        "ado-steal-blue": "#2F4E61",
        "ado-white-80": "rgba(255, 255, 255, 0.08)",
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      fontFamily: {
        "gotham-pro": ["var(--font-gotham-pro)", "sans-serif"],
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        bold: "700",
      },
      boxShadow: {
        charcoal: "0px 8px 16px 0px rgba(13, 14, 15, 0.10)",
        green: "0px 4px 8px 0px rgba(0, 208, 15, 0.1)",
        strongsmoke: "0px 8px 16px rgba(13, 14, 15, 0.10)",
      },
      scrollbar: {
        hide: "::-webkit-scrollbar { display: none; }",
      },
    },
  },
  plugins: [],
} satisfies Config;
