import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Container from "@/components/Container";
import ClientProvider from "@/components/clientProvider";

const gothamProFont = localFont({
  src: [
    {
      path: "../../font/gothampro.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../font/gothampro_medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../font/gothampro_bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-gotham-pro",
});

export const metadata: Metadata = {
  title: "ADO",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: "es" | "en" };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${gothamProFont.variable} antialiased`}>
        <ClientProvider>
          <NextIntlClientProvider messages={messages}>
            <Container>{children}</Container>
          </NextIntlClientProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
